services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: 'unless-stopped'
    network_mode: 'bridge'
    volumes:
      - /home/justus/docker-compose/prowlarr/data:/config
    ports:
      - 9696:9696
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC