services:
  jotty:
    image: "ghcr.io/fccview/jotty:latest"
    container_name: "jotty"
    restart: "unless-stopped"
    user: "1000:1000"
    ports:
      - "127.0.0.1:1122:3000"
    volumes:
      - ../../storage/jotty/data:/app/data:rw
      - ../../storage/jotty/config:/app/config:ro
      - ../../storage/jotty/cache:/app/.next/cache:rw
    environment:
      - NODE_ENV=production
      - HTTPS=true
      - APP_URL=https://notes.justus0405.com
      - SERVE_PUBLIC_IMAGES=no
      - SERVE_PUBLIC_FILES=no
