services:
  uptime-kuma:
    image: "louislam/uptime-kuma:2"
    container_name: "uptime-kuma"
    restart: "unless-stopped"
    ports:
      - "3001:3001"
    volumes:
      - ../../storage/uptime-kuma/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
  nginx-status-page:
    image: "nginx:alpine"
    container_name: "nginx-status-page"
    restart: "unless-stopped"
    ports:
      - "3002:80"
