services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: 'unless-stopped'
    network_mode: 'bridge'
    volumes:
      - /home/justus/docker-compose/qbittorrent/appdata:/config
      - /home/justus/docker-compose/qbittorrent/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881

# [Fix: no login]
# nano ~/qbittorrent/appdata/qBittorrent/qBittorrent.conf
# WebUI\Password_PBKDF2="@ByteArray(ARQ77eY1NUZaQsuDHbIMCA==:0WMRkYTUWVT9wVvdDtHAjU9b3b7uB8NR1Gur2hmQCvCDpm39Q+PsJRJPaCU51dEiz+dTzh8qbPsL8WkFljQYFQ==)"
# User: admin
# Pass: adminadmin